### ISSUE TITLE
for java

### ISSUE THREAD

**Issue by kadhumalrubaye** [aballano/kursor#2]
can i use it for java language??

**Comment by aballano** [comment]
Hi @kazimlumia, technically yes. The Kotlin code would generate something like an utils class, so you could call those methods from Java, although I'm not sure if they would be as useful. But feel free to try out :)

**Comment by kadhumalrubaye** [comment]
thank youbro but when i pas the dependencies i got this massage 
Error:(27, 13) Failed to resolve: com.github.aballano:kursor:x.x.x
<a href="openFile:C:/Users/kazim/AndroidStudioProjects/DBSM/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by aballano** [comment]
Yep, you have to replace the x.x.x with the real version, so it would be:

com.github.aballano:kursor:1.0
